AWSTemplateFormatVersion: 2010-09-09
Resources:

  MYabobra:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-02fe94dee086c0c37"
      InstanceType: t2.micro
      KeyName: 1sti-training
      SubnetId: "subnet-0cf6a0111c61412d6"
      Tags: 
      - Key: Name
        Value: 1sti-training

  AbobraSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH and general HTTP Access
      VpcId: "vpc-084e180dbf562c386"
      SecurityGroupIngress:

        # Configure HTTP access
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        # Configure (and limit) SSH access
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
