
on:
  push
jobs:
  listEC2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]
    steps:
      - uses: /RibeiroLeo/VM-ec2@v1
      # All commands after this point have access to the AWS CLI
      - run: aws ec2 ls
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID="AKIAUEAOH7SEZRZ3YOXY" }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY="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" }}
